Add abstract evaluator
picselliahq/picsellia-training-engine pull request #4
Opened 2023-05-24 16:46 UTC by SoniaGrh

Hello,
I pull request to have an opinion on the clarity of code, to have tips to clarify it as well as any remarks that may cross your mind.
Thanks a lot!

2023-05-25 08:11 UTC, n7-Thomas requested changes
some modif mais c'est en partie my bad

2023-05-25 08:11 UTC, n7-Thomas commented on evaluator/type_formatter.py
> +        self, asset: Asset, prediction: yolo.engine.results.Results, get_picsellia_label
mauvaise signature

2023-05-25 08:11 UTC, n7-Thomas commented on evaluator/framework_formatter.py
> +    def _format_boxes(cls, asset: Asset, prediction) -> List[int]:
ça renvoie une liste de int ?

2023-05-25 08:11 UTC, n7-Thomas commented on evaluator/yolo_evaluator.py
> +                f"Impossible to load saved model located at: {self.model_weights_path}"
c'est plus un paramètre de la classe model_weights_path

2023-05-25 08:17 UTC, revfyawo-picsell commented
- Stop adding "personnal" files to the `.gitignore`. Pick a name for test files you use across the repo and only add this one to the gitignore, or better, don't test from files within this repo.
- Sort your imports. This could be done with a pre-commit hook, or by using PyCharm / the right extension for VSCode.

2023-05-26 13:41 UTC, n7-Thomas commented on evaluator/abstract_evaluator.py
> +            self._confidence_threshold = confidence_threshold
A mon avis tu dois pas set le confidence threshold ici, mais plutôt le passer dans les paramètres de evaluate.
Techniquement là si tu fais 
X = Evaluator(confidence=0.2)
X.eval(0.3)
X.eval()

le deuxième eval va se faire à 0.3 alros que t'attendrais 0.2

2023-05-26 13:41 UTC, n7-Thomas commented on evaluator/framework_formatter.py
> +    def format_polygons(self, prediction):
j'préfère écrire 
```
if prediction.masks is None:
   return []
polygons = prediction.masks.xy
casted_polygons = list(map(lambda polygon: polygon.astype(int), polygons))
return list(map(lambda polygon: polygon.tolist(), casted_polygons))

```
mais c'est que ma préférence perso

2023-05-26 13:41 UTC, n7-Thomas commented on evaluator/type_formatter.py
> +        picsellia_predictions = {}
tu peux retourner directement le dico je trouve ça plus lisible (valable pour les 3 format_predictions)

2023-05-26 13:41 UTC, n7-Thomas commented on evaluator/type_formatter.py
> +    def format_evaluation(self, picsellia_prediction):
tu peux directement renvoyer le tuple comme t'as fait sur Segm

2023-05-26 14:53 UTC, SoniaGrh commented on evaluator/type_formatter.py
> +    def format_evaluation(self, picsellia_prediction):
Pour la segmentation, le add evaluation attend "Tuple[List[int], Label, float]" alors que pour la détection il attend "Tuple[int, int, int, int, Label, float]" ce qui est déroutant d'ailleurs. 
Du coup je préfère créer append le label et le score à la list de boxe puis transformer la liste en tuple

2023-05-26 14:57 UTC, SoniaGrh commented on evaluator/framework_formatter.py
> +    def format_polygons(self, prediction):
j'ai fait ça pck quand je fais .astype(int) ça donne pas la même chose que quand je cast les éléments de ma liste en int avec la fonction que j'ai faite

2023-05-26 14:58 UTC, SoniaGrh commented on evaluator/abstract_evaluator.py
> +            self._confidence_threshold = confidence_threshold
je pensais que c'était le but pour pouvoir lancer plusieurs évaluations avec des thresholds potentiellement différents

2023-05-29 14:33 UTC, merged